TARGET	= libmatmult.so
LIBSRCS	= 
LIBOBJS	= matmul_c.o

#-O3 -funroll-loops -flto -march=native -mfpmath=sse
OPT	= -g -O3 -funroll-loops -march=native -mfpmath=sse
PIC	= -fPIC

CC	= gcc
CFLAGS= $(OPT) $(PIC) $(XOPTS)

SOFLAGS = -shared 
XLIBS	= -L/usr/lib64/atlas -lsatlas

$(TARGET): $(LIBOBJS)
	$(CC) -o $@ $(SOFLAGS) $(LIBOBJS) $(XLIBS)

clean:
	@/bin/rm -f core core.* $(LIBOBJS) 
